### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by liampauling** [MarkusLinjamaki/betFairAndFun#1]
I can see your appKey and sessionToken

**Comment by MarkusLinjamaki** [comment]
Hi!
Thank you for let me know.
Best Regards: Markus

________________________________
Lähettäjä: Liam <notifications@github.com>
Lähetetty: tiistai 26. tammikuuta 2021 17.52
Vastaanottaja: MarkusLinjamaki/betFairAndFun <betFairAndFun@noreply.github.com>
Kopio: Subscribed <subscribed@noreply.github.com>
Aihe: [MarkusLinjamaki/betFairAndFun] Security Issue (#1)


I can see your appKey and sessionToken
